### ISSUE TITLE
issue with routing

### ISSUE THREAD

**Issue by orlandodemauro** [PlaceMe-SAS/single-spa-angular-cli#2]
dear @robinComa ,

first of all thanks for your amazing work. what I´m trying to do is using your example repo to create a scheleton for my webpage.

first of all i replaced the app1 with a ap2 (todoapp in angular-cli) to get familiar with the single-spa architecture.
[https://github.com/orlandodemauro/single-spa-angular-cli-examples](https://github.com/orlandodemauro/single-spa-angular-cli-examples)

everything looks working, but i´m having an issue with routing. 

I´ll try to explain: the todo app is using routing to filter the tasks that are active, completed, an it is working using the navigation buttons inside the tosoApp. the proble is when i use the menuApp navigation button.
let´s imagine that i click on the completed filter (url: http://localhost:8080/#/app2/completed) the todos are filtered, if i click on the menuApp app2 button (url: http://localhost:8080/#/app2/all) the data are up to date but the view is not re-rendered. 

![todoapp2](https://user-images.githubusercontent.com/14298717/36219316-3e8b2086-11b7-11e8-9dff-ac970c2824e3.gif)

do you think that there is something that is blocking the re-render? because the data are updated as shown in the console.

thank you for any suggestion

**Comment by robinComa** [comment]
Hello @orlandodemauro 
sorry for the delay, I try your code and I have the same issue.
I propose a little patch for the moment with this PR : 
[https://github.com/orlandodemauro/single-spa-angular-cli-examples/pull/1/commits](https://github.com/orlandodemauro/single-spa-angular-cli-examples/pull/1/commits)

I think this issue is because angular trigger the change detection with all lot of setter and events like click, sroll, resize... So the click is outside the app2 todo app, and I think the change detection trigger is not called
For the moment I have no idea to fixing the issue without this patch, but maybe in the future.
What do you think about this "solution"?

Regards,

**Comment by orlandodemauro** [comment]
hi @robinComa ,

first of all thank you so much for your time and your reply.about the issue i thought to the same workaround yesterday so it is fine for me. I didn't apply it before because I was worried it was an issue with the singleSpaAngularCliRouter or how thesingle-spa-angular-cli module handle the routing, I was thinking that maybe something in the module was blocking the re-render because the data was changing but the change detection wasn't triggered.

thank you so much. i do appreciate it
