### ISSUE TITLE
Add Option to leave apps mounted

### ISSUE THREAD

**Issue by bfaulk96** [PlaceMe-SAS/single-spa-angular-cli#25]
Currently, child apps are unmounted whenever the user navigates away from them. For large child apps, this causes long load times every time a user navigates back to a child app. If there was an option to leave an app mounted, only the initial load would be necessary.
I'm not sure how to set up passing options into the loader, but my team has manually cloned this repo into our project and turned off unmounting, so I could help with that.

**Comment by filoxo** [comment]
Just a quick observation/consideration: unmounting and then remounting an app shouldn't cause any additional load since the child file should already be in the browser cache. Long load times may be a problem within the child app (eg. waiting for data retrieval before rendering anything to the page) and not necessarily with it being a singlespa child.

**Comment by bfaulk96** [comment]
I apologize, I may have misspoken in my initial statement. What you said is correct. The long load times have to do with data retrieval from api calls. That still presents the problem though: we do not want to re-retrieve the same data from an API every time we mount the app, and by leaving the apps mounted, the data stays where it is.

**Comment by bfaulk96** [comment]
This is fixed by PR #28

**Comment by bfaulk96** [comment]
Unfortunately due to our specific use case, it's not viable to do all data retrieval in the parent app.

**Comment by TheMcMurder** [comment]
@bfaulk96 we'd have to discuss this feature in greater depth, but I'd like to understand a bit more. It seems like you are trying to solve what is ultimately an API/Application problem by changing the fundamental design of single-spa. When an application isn't mounted single-spa prevents events from hitting the application by design, leaving an application mounted will almost certainly cause some larger performance issues.

There are a few options I see immediately and @filoxo mentioned one of them.
1) Have the slow data request done by the single-spa-config/parent-application
2) Have the data request cached by the browser
3) Make the data request during the lifecycle functions only if the data isn't already cached by the project.
4) Have a shared data store that the child applications have access to

**Comment by bfaulk96** [comment]
What performance issues do you foresee? What if, in a future single-spa update, you add the ability to keep the first N apps mounted? That way, you could keep say, 5 apps mounted, but after 6 the oldest would be unmounted? Either way, can we silently add this workaround to this helper library for now? It won't affect anyone else, and improves performance for our use-case.

**Comment by TheMcMurder** [comment]
> What performance issues do you foresee?

Events are being sent to an application that doesn't need them. Those events could easily trigger side effects that would be very difficult to debug
> What if, in a future single-spa update, you add the ability to keep the first N apps mounted? That way, you could keep say, 5 apps mounted, but after 6 the oldest would be unmounted? 

Again we're talking about making a major change to the design of `single-spa` to support a use case that is already supported, I don't (yet) see an advantage to this approach versus the common approaches I've mentioned above
> Either way, can we silently add this workaround to this helper library for now? It won't affect anyone else, and improves performance for our use-case.

`single-spa-angular-cli` isn't my project so that's up to @robinComa but IMHO I don't see how adding this feature will benefit you beyond the other options and I can easily see how it could negatively impact others in the future. *There are ways to get the exact same performance improvements you want without fundamentally changing `single-spa` and they exist right now in javascript*

**Comment by joeldenning** [comment]
Leaving apps mounted even after their activity function says they shouldn't be mounted goes against single-spa's ideology. The problem you're describing with a slow network request needing to be cached can be solved in a lot of other ways -- I think those methods are preferred.

**Comment by bfaulk96** [comment]
Thanks for the speedy and thorough replies, @TheMcMurder and @joeldenning. I think I understand where you're coming from.

**Comment by joeldenning** [comment]
This project is deprecated (see #36). Use [single-spa-angular@3](https://github.com/CanopyTax/single-spa-angular/), instead.
