### ISSUE TITLE
Error zone.js in ie11

### ISSUE THREAD

**Issue by Adriankaizen** [PlaceMe-SAS/single-spa-angular-cli#29]
Hello excellent project, as the problem that solves that is to say, to be seen separately, tell me that this error is to run the application separately, I think by the zone.js

![image](https://user-images.githubusercontent.com/11823769/43417280-2d6fe446-9400-11e8-9710-f53f3fcfa714.png)

![image](https://user-images.githubusercontent.com/11823769/43417335-5536f500-9400-11e8-9786-ac19e046cd18.png)

It should be mentioned that it is the application of angular separately, thanks for tu suggestions

**Comment by joeldenning** [comment]
Apologies for the slow response here -- this looks like it is related to https://github.com/angular/zone.js/issues/1031.

**Comment by nickfeng1982** [comment]
the best solution to deal with zone.js issue so far is

1, comment out import 'zone.js/dist/zone'; from the pollyfill.ts
2, add 	<script src="https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.8.29/zone.js"></script> into the index.html

since angular will compile zone.js into the bundle so this way the spa framework won't load zone.js from the child, and only the shell has one zone.js file acting.

**Comment by joeldenning** [comment]
This project is deprecated (see #36). Use [single-spa-angular@3](https://github.com/CanopyTax/single-spa-angular/), instead.
